### ISSUE TITLE
Remove start script name from the UI and config files

### ISSUE THREAD

**Issue by Gama11** [klausdorer/magmaChallenge#5]
Instead, it should be assumed that the directory contains a file named `start.sh` (like it already does with the `kill.sh` files).
This would simplify the UI and make the behavior consistent for both required scripts.

**Comment by klausdorer** [comment]
I would prefer that the name of the script is not start.sh to allow different scripts for the competition and the challenge in the same folder. For kill this is not an issue since it should be the same script for both. Something like startChallenge.sh or similar. Do not forget to update the description on github ;-)
